<a href="https://colab.research.google.com/github/plzstudy/Google_Colab_Code/blob/master/TensorFlow_Axis_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
import numpy as np

In [0]:
a=[
    [
        [1,2,3,4],
        [3,4,5,6],
        [7,8,9,10]
    ],
    
    [
        [11,12,13,14],
        [15,16,17,18],
        [19,20,21,22]
    ]
]

In [0]:
print(a)

[[[1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 10]], [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]]


In [0]:
b=np.array(a)
print(a)

[[[1, 2, 3, 4], [3, 4, 5, 6], [7, 8, 9, 10]], [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]]


In [0]:
b.shape

(2, 3, 4)

In [0]:
c=tf.constant(b)

In [0]:
print(c)

Tensor("Const:0", shape=(2, 3, 4), dtype=int64)


In [0]:
sess=tf.Session()

In [0]:
print(sess.run(c))

[[[ 1  2  3  4]
  [ 3  4  5  6]
  [ 7  8  9 10]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [0]:
print(sess.run(tf.reduce_sum(c)))

260


In [0]:
print(sess.run(tf.reduce_sum(c,0))) # 차원의 합 (Axis=0)

[[12 14 16 18]
 [18 20 22 24]
 [26 28 30 32]]


In [0]:
print(sess.run(tf.reduce_sum(c,1))) # 열의 합 (Axis=1)

[[11 14 17 20]
 [45 48 51 54]]


In [0]:
print(sess.run(tf.reduce_sum(c,2))) # 행의 합 (Axis=2)

[[10 18 34]
 [50 66 82]]


In [0]:
# 결론적으로, shape에 따라서 Axis를 따르지 않는다는 것을 보여주고 있음
# shape는 0:차원, 1:행, 2:열 / tf.reduce_sum은 0:차원, 1:열, 2:행